package com.example.whatToEat.data.local.mapper

import com.example.whatToEat.data.local.models.MealEntity
import com.example.whatToEat.domain.model.IngredientMeasurement
import com.example.whatToEat.domain.model.Meal


fun MealEntity.mealEntityToMeal(): Meal {
    return Meal(
        uid = this.uid!!, // autogenerated uid
        apiId = this.apiId,
        mealName = this.mealName,
        category = this.category,
        area = this.area,
        instructions = this.instructions,
        thumbnail = this.thumbnail,
        youtube = this.youtube,
        fromDB = true,
        ingredientMeasurementList = this.ingredientMeasurementList.ingredientMeasurements.map {
            IngredientMeasurement(it.ingredient, it.measurement)
        }
    )
}